# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'db/*schema.rb'
    - 'db/seeds.rb'
    - 'doc/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'workspace/**/*'
    - 'test/**/*'

  DisplayCopNames: true
  DisplayStyleGuide: true

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
