default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Match0327
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: qiita_team_development

test:
  <<: *default
  database: qiita_team_test

production:
  <<: *default
  database: qiita_team_production
  username: qiita_team
  password: <%= ENV['QIITA_TEAM_DATABASE_PASSWORD'] %>
